ALTER TABLE column_info ADD CI_HOME INT;

ALTER TABLE column_info ADD CI_DESC VARCHAR(1024);

ALTER TABLE user_info ADD UI_CN VARCHAR(128);

ALTER TABLE COLUMN_INFO ADD CI_URL VARCHAR(256);

ALTER TABLE OFFICE_DETAIL MODIFY COLUMN OD_ORDER int DEFAULT '1';

ALTER TABLE OFFICE_DETAIL ADD OD_NOTE VARCHAR(128);

ALTER TABLE OFFICE_DETAIL ADD OD_TYPE VARCHAR(128);
