ALTER TABLE LEADER_INFO MODIFY COLUMN LI_RANG varchar(4096);

ALTER TABLE LEADER_INFO MODIFY COLUMN LI_RESUME varchar(4096);

ALTER TABLE LEADER_INFO MODIFY COLUMN LI_DESC varchar(4096);

ALTER TABLE DOCTOR_INFO DROP COLUMN OS_ID;

ALTER TABLE DOCTOR_INFO ADD OS_EXPERT_ID INT;

ALTER TABLE DOCTOR_INFO ADD OS_FAMOUS_ID INT;

ALTER TABLE DOCTOR_INFO ADD DI_TAL_TYPE VARCHAR(64);