ALTER TABLE ONLINE_CONSULTATION ADD OS_CLICKS INT DEFAULT '0';

ALTER TABLE CONTENT_DETAIL ADD CD_CLICKS INT DEFAULT '0';

ALTER TABLE CONTENT_DETAIL ADD CD_CONTENT VARCHAR(4096);

ALTER TABLE TALENT_GENRE ADD TG_CODE VARCHAR(16);


