ALTER TABLE OFFICE_DETAIL DROP COLUMN OD_DESC;
ALTER TABLE OFFICE_DETAIL ADD OD_DESC VARCHAR(4096);

ALTER TABLE OFFICE_DETAIL DROP COLUMN OD_ACADEMIC_POSITION;
ALTER TABLE OFFICE_DETAIL ADD OD_ACADEMIC_POSITION VARCHAR(4096);

ALTER TABLE OFFICE_DETAIL DROP COLUMN OD_TECH_ADV;
ALTER TABLE OFFICE_DETAIL ADD OD_TECH_ADV VARCHAR(4096);
 
ALTER TABLE OFFICE_DETAIL DROP COLUMN OD_RESEARCH_DIRECTION;
ALTER TABLE OFFICE_DETAIL ADD OD_RESEARCH_DIRECTION VARCHAR(4096);
