ALTER TABLE ONLINE_CONSULTATION ADD OC_SEX INT;

ALTER TABLE ONLINE_CONSULTATION ADD OS_ANSWER VARCHAR(512);

ALTER TABLE LEADER_INFO ADD LI_HOLD_PERIOD VARCHAR(32);

ALTER TABLE COLUMN_INFO ADD CI_NEWS INT DEFAULT '1';

ALTER TABLE COLUMN_INFO DROP COLUMN CI_HOME;