ALTER TABLE OFFICE_DETAIL MODIFY COLUMN OD_BED_COUNTER int DEFAULT '0';

ALTER TABLE CONTENT_DETAIL MODIFY COLUMN CD_AUDIT_RESULT int DEFAULT '1';

ALTER TABLE CONTENT_DETAIL MODIFY COLUMN CD_ORDER int DEFAULT '1';


DROP TABLE ONLINE_CONSULTATION;
CREATE TABLE ONLINE_CONSULTATION  (
   OC_ID                 INTEGER               NOT NULL  AUTO_INCREMENT,
   OC_POST_TIME          DATETIME,
   OC_REQUEST_OFFICE     INTEGER,
   OC_RECEIVE_OFFICE     INTEGER,
   OC_POST_NAME          VARCHAR(64),
   OC_POST_AGE           INTEGER,
   OC_POST_SUBJECT       VARCHAR(64),
   OC_DESC               VARCHAR(512),
   OS_ANSWERED           INTEGER,
   OS_ANSWER_OFFICE      INTEGER,
   OS_ANSWER_TIME        DATETIME,
   OS_TYPICAL            INTEGER,
   PRIMARY KEY (OC_ID)
) type=InnoDB;

alter table DOCTOR_INFO auto_increment= 1000;
