set names utf8;
/*inti the GROUP_MEMBER table*/
truncate table GROUP_MEMBER;
INSERT INTO GROUP_MEMBER(GM_ID, GM_NAME, GM_NAME_SHORT, GM_ADDRESS, GM_POSTAL, GM_TELEPHONE, GM_FAX, GM_EMAIL) VALUES(1000, '杭州市第一人民医院', '市一', '', '', '', '', '');
INSERT INTO GROUP_MEMBER(GM_ID, GM_NAME, GM_NAME_SHORT, GM_ADDRESS, GM_POSTAL, GM_TELEPHONE, GM_FAX, GM_EMAIL) VALUES(1001, '杭州市妇幼保健院', '妇幼', '', '', '', '', '');
INSERT INTO GROUP_MEMBER(GM_ID, GM_NAME, GM_NAME_SHORT, GM_ADDRESS, GM_POSTAL, GM_TELEPHONE, GM_FAX, GM_EMAIL) VALUES(1002, '杭州市肿瘤医院（吴山院区）', '吴山', '', '', '', '', '');
INSERT INTO GROUP_MEMBER(GM_ID, GM_NAME, GM_NAME_SHORT, GM_ADDRESS, GM_POSTAL, GM_TELEPHONE, GM_FAX, GM_EMAIL) VALUES(1003, '杭州市老年病医院（城北院区）', '城北', '', '', '', '', '');
INSERT INTO GROUP_MEMBER(GM_ID, GM_NAME, GM_NAME_SHORT, GM_ADDRESS, GM_POSTAL, GM_TELEPHONE, GM_FAX, GM_EMAIL) VALUES(1004, '杭州市妇女医院（钱江新城院区）', '钱江', '', '', '', '', '');
INSERT INTO GROUP_MEMBER(GM_ID, GM_NAME, GM_NAME_SHORT, GM_ADDRESS, GM_POSTAL, GM_TELEPHONE, GM_FAX, GM_EMAIL) VALUES(1005, '五云山健康管理中心', '五云山', '', '', '', '', '');

/*inti the OFFICE_DETAIL table*/
truncate table OFFICE_DETAIL;
INSERT INTO OFFICE_DETAIL(OD_ID, OD_NAME, OD_ORDER, OD_BELONG, OD_IN_CHARGE, OD_TELEPHONE, OD_EMAIL, OD_SITE, OD_LOCATION, OD_BED_COUNTER) VALUES(1000, '肿瘤内科', 20, 1000, '潘月龙', '0571-87065701-21681', 'zlnk@126.com', '', '市一医院2号楼6楼', 70);
INSERT INTO OFFICE_DETAIL(OD_ID, OD_NAME, OD_ORDER, OD_BELONG, OD_IN_CHARGE, OD_TELEPHONE, OD_EMAIL, OD_SITE, OD_LOCATION, OD_BED_COUNTER) VALUES(1001, '中医师', 20, 1000, '顾文平', '0571-87065701-21681', 'gwp@126.com', '', '市一医院2号楼6楼', 70);

/*inti the COLUMN_INFO table*/
truncate table COLUMN_INFO;
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1000, '网站首页','',1,'', 0, 0,'', sysdate(), 1000);

INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1100, '医院概览','',1,'',0, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1101, '集团导航','',2,'', 1100, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1102, '医院简介','',2, '',1100, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1103, '组织结构','',2, '',1100, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1104, '院长寄语','',2, '',1100, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1105, '现任领导','',2, '',1100, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1106, '历任领导','',2,'', 1100, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1107, '院务公开','',2,'', 1100, 2000,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1108, '医院历史','',2,'', 1100, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1109, '重大记事','',2, '',1100, 2000,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1110, '联系我们','',2, '',1100, 0,'', sysdate(), 1000);

INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1200, '信息中心','',1, '',0, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1201, '医院公告','',2, '',1200, 2000,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1202, '医院新闻','',2,'', 1200, 1000,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1203, '集团动态','',2,'', 1200, 2000,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1204, '多媒体中心','',2,'', 1200, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1205, '人才招聘','',2, '',1200, 4000,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1206, '招标采购','',2,'', 1200, 2000,'', sysdate(), 1000);

INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1300, '患者服务中心','',1,'', 0, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1301, '专家查询','',2, '',1300, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1302, '就医流程','',2,'', 1300, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1303, '就医须知','',2, '',1300, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1304, '楼宇分布','',2,'', 1300, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1305, '医院规章','',2,'', 1300, 2000,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1306, '特色服务','',2,'', 1300, 2000,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1307, '交通指南','',2, '',1300, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1308, '预约挂号','',2, '',1300, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1309, '在线咨询中心','',2, '',1300, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1310, '化验查询','',2, '',1300, 0,'', sysdate(), 1000);

INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1400, '科室导航','',1,'', 0, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1401, '临床科室','',2, '',1400, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1402, '省市重点','',2,'', 1400, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1403, '特色专科','',2,'', 1400, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1404, '医技科室','',2,'', 1400, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1405, '只能科室','',2, '',1400, 0,'', sysdate(), 1000);

INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1500, '专家介绍','',1, '',0, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1501, '专家一览','',2, '',1500, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1502, '名医门诊','',2, '',1500, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1503, '博士生导师','',2,'', 1500, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1504, '硕士生导师','',2, '',1500, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1505, '151人才','',2,'', 1500, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1506, '131人才','',2,'', 1500, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1507, '南医大教授','',2,'', 1500, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1508, '南医大副教授','',2, '',1500, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1509, '浙江省医学会主委/副主委','',2, '',1500, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1510, '门诊排班信息','',2, '',1500, 0,'', sysdate(), 1000);

INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1600, '科研学术','',1,'', 0, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1601, '科研动态','',2, '',1600, 2000,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1602, '科技成果','',2, '',1600, 2000,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1603, '高新设备','',2, '',1600, 2000,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1604, '学术交流','',2, '',1600, 2000,'', sysdate(), 1000);

INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1700, '医院文化和教育','',1,'', 0, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1701, '党建团建','',2, '',1700, 2000,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1702, '志愿者之家','',2, '',1700, 3000,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1703, '护理天地','',2,'', 1700, 2000,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1704, '青年文明号','',2,'', 1700, 2000,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1705, '医院期刊','',2,'', 1700, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1706, '健康大讲堂','',2, '',1700, 2000,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1707, '康复沙龙','',2,'', 1700, 2000,'', sysdate(), 1000);

INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1800, '杭州市癌症中心','',1, '',0, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(1900, '杭州市心脑血管病诊治中心','',1,'', 0, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(2000, '杭州市高危孕产妇急救中心','',1, '',0, 0,'', sysdate(), 1000);
INSERT INTO COLUMN_INFO(CI_ID, CI_TITAL, CI_ICON, CI_LEVEL,CI_URL,CI_PARENT, CI_CATE, CI_DESC, CI_ADD_TIME, CI_ADDER) VALUES(2100, '杭州市健康管理中心','',1, '',0, 0,'', sysdate(), 1000);
/*inti the OFFICE_GENRE table*/
truncate table OFFICE_GENRE;
INSERT INTO OFFICE_GENRE(OG_ID, OG_NAME, OG_CODE, OG_DESC, OG_LEVEL, OG_PARENT) VALUES(1000, '临床科室', 'lcks', '', 1, 0);
INSERT INTO OFFICE_GENRE(OG_ID, OG_NAME, OG_CODE, OG_DESC, OG_LEVEL, OG_PARENT) VALUES(1001, '省市重点', 'sszd', '', 1, 0);
INSERT INTO OFFICE_GENRE(OG_ID, OG_NAME, OG_CODE, OG_DESC, OG_LEVEL, OG_PARENT) VALUES(1002, '医技科室', 'yjks', '', 1, 0);
INSERT INTO OFFICE_GENRE(OG_ID, OG_NAME, OG_CODE, OG_DESC, OG_LEVEL, OG_PARENT) VALUES(1003, '特色专科', 'tszk', '', 1, 0);
INSERT INTO OFFICE_GENRE(OG_ID, OG_NAME, OG_CODE, OG_DESC, OG_LEVEL, OG_PARENT) VALUES(1004, '职能科室', 'znks', '', 1, 0);
INSERT INTO OFFICE_GENRE(OG_ID, OG_NAME, OG_CODE, OG_DESC, OG_LEVEL, OG_PARENT) VALUES(1005, '质控中心', 'zkzx', '', 1, 0);
INSERT INTO OFFICE_GENRE(OG_ID, OG_NAME, OG_CODE, OG_DESC, OG_LEVEL, OG_PARENT) VALUES(1006, '诊疗中心', 'zlzx', '', 1, 0);

/*inti the TALENT_GENRE table*/
truncate table TALENT_GENRE;
INSERT INTO TALENT_GENRE(TG_ID, TG_TYPE, TG_NAME, TG_DESC) VALUES(1000, 1, '博士生导师', '');
INSERT INTO TALENT_GENRE(TG_ID, TG_TYPE, TG_NAME, TG_DESC) VALUES(1001, 1, '硕士生导师', '');
INSERT INTO TALENT_GENRE(TG_ID, TG_TYPE, TG_NAME, TG_DESC) VALUES(1002, 1, '151人才', '');
INSERT INTO TALENT_GENRE(TG_ID, TG_TYPE, TG_NAME, TG_DESC) VALUES(1003, 1, '131人才', '');
INSERT INTO TALENT_GENRE(TG_ID, TG_TYPE, TG_NAME, TG_DESC) VALUES(1004, 1, '南医大学教授', '');
INSERT INTO TALENT_GENRE(TG_ID, TG_TYPE, TG_NAME, TG_DESC) VALUES(1005, 1, '南医大学副教授', '');
INSERT INTO TALENT_GENRE(TG_ID, TG_TYPE, TG_NAME, TG_DESC) VALUES(1006, 1, '浙江省医学会主委/副主委', '');
INSERT INTO TALENT_GENRE(TG_ID, TG_TYPE, TG_NAME, TG_DESC) VALUES(1007, 1, '杭州市医学会主任', '');



